version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file: prod.env
  web:
    env_file: prod.env
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgresdata: