version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - dev.env
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - dev.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  manage:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: manage
    volumes:
      - .:/code
    env_file:
      - dev.env
    depends_on: 
      - db
    working_dir: /code
    entrypoint: ['python', 'manage.py']
volumes:
  pgdata: